title: "Richard Souvenir"
description: "Professor, Computer & Information Sciences, Temple University"
url: "https://richardsouvenir.github.io"
baseurl: ""          # user site -> empty
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins: [jekyll-feed, jekyll-sitemap]
markdown: kramdown
permalink: /:categories/:title/
collections:          # lets you add pages outside _posts
  pages:
    output: true

# Top navigation
main:
  - title: "Home"
    url: /
  - title: "News"
    url: /news/
  - title: "Research"
    url: /research/
  - title: "Teaching"
    url: /teaching/
  - title: "Publications"
    url: /publications/
